//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImHereNonProfit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppModelContainer : DbContext
    {
        public AppModelContainer()
            : base("name=AppModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Committee> Committees { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<CommitteeActivity> CommitteeActivities { get; set; }
        public virtual DbSet<CommitteeReport> CommitteeReports { get; set; }
        public virtual DbSet<CommitteeDocument> CommitteeDocuments { get; set; }
        public virtual DbSet<CommitteeExpens> CommitteeExpenses { get; set; }
        public virtual DbSet<BasicUser> BasicUsers { get; set; }
    }
}
