//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImHereNonProfit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeExpens
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public string Currency { get; set; }
        public System.DateTime Date { get; set; }
        public int CommitteeId { get; set; }
        public string Description { get; set; }
    
        public virtual Committee ForCommittee { get; set; }
    }
}
