//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImHereNonProfit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Committee
    {
        public Committee()
        {
            this.Activities = new HashSet<CommitteeActivity>();
            this.CommitteeReports = new HashSet<CommitteeReport>();
            this.CommitteeDocuments = new HashSet<CommitteeDocument>();
            this.CommitteeExpenses = new HashSet<CommitteeExpens>();
            this.Members = new HashSet<MemberUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CurrentYearBudget { get; set; }
        public int ChairId { get; set; }
    
        public virtual ICollection<CommitteeActivity> Activities { get; set; }
        public virtual ICollection<CommitteeReport> CommitteeReports { get; set; }
        public virtual ICollection<CommitteeDocument> CommitteeDocuments { get; set; }
        public virtual ICollection<CommitteeExpens> CommitteeExpenses { get; set; }
        public virtual ICollection<MemberUser> Members { get; set; }
        public virtual ExecutiveUser Chair { get; set; }
    }
}
