//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImHereNonProfit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeActivity
    {
        public int Id { get; set; }
        public int CommiteeId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public System.DateTime ReportedDate { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
    
        public virtual Committee Commitee { get; set; }
    }
}
